### ISSUE TITLE
What will happen if re-connect pass-through disk

### ISSUE THREAD

**Issue by ps1x** [vdsm/virtual-dsm#673]
Hello again!

According to docs, pass-through disk should be completely (though its written not always) empty for pass-through to work
```
Please note that the device needs to be totally empty (without any partition table) otherwise DSM does not always format it into a volume.

Do NOT use this feature with the goal of sharing files from the host, they will all be lost without warning when DSM creates the volume.
```

Questions are: 
1) What will happen if i remove disk from docker-compose entry and then bring it back to the same virtual dsm?
2) What will happen if i remove disk from one docker-compose virtual dsm and bring to another virtual dsm?
3) Is it possible to somehow mount it to normal linux-system after DSM created its btrfs filesystem on it?
4) What will happen if (3) is possible and then you bring it back to same virtual dsm?

**Comment by GreatApo** [comment]
Re-commenting as I had a drive removed and reconnected and the drive was not recognized automatically. I shared the drive through the mount station but all the files are gone.

This can easily happen especially since the disk names are not constants (e.g. sdb can change to sdc). I did change the device passthrough using the drive UUID but the files are already gone.

If there is any way to remount it correctly or recover the files, let me know.

**Comment by GreatApo** [comment]
> Hopefully this serves as a reminder to the user that device names are not static, together with the UUID in the example.

Will definitely help.

> It's very annoying that the standard `mount` command in Linux cannot read the Synology partition data (or BTRFS headers, I am not sure). A lot of their customers already complained about that. Maybe on the Synology forums there are some tricks how to read a drive with external tools.

They are definitely using a custom implementation which is quite bad.
